### ISSUE TITLE
Basic site setup details please

### ISSUE THREAD

**Issue by rrodstein** [katmore/clientcal#1]
Hi,

Great looking project! Thank you in advance for your support.

Could you please provide some tips on how to setup, and get the project running? 

i.e. I followed the README instructions, and was able to run the database installer script, moved the clientcal directoty into /var/www/html/clientcal, setup the virtual host file, i.e. 

```
Listen 8888

<VirtualHost *:8888>
        ServerAdmin infoclientcal@.com

        DocumentRoot /var/www/html/clientcal/app/config/clientcal
        <Directory "/var/www/html/clientcal/app/config/clientcal">
                AllowOverride All
                Require local
                Satisfy Any
        </Directory>

        ErrorLog /var/log/apache2/clientcal_error.log

        # Possible values include: debug, info, notice, warn, error, crit,
        # alert, emerg.
        LogLevel warn

        CustomLog /var/log/apache2/clientcal_access.log combined

</VirtualHost>
```
we also tried this, same result:

```
Listen 8888

<VirtualHost *:8888>
        ServerAdmin info@clientcal.com

        DocumentRoot /var/www/html/clientcal/web
        <Directory "/var/www/html/clientcal/web">
                AllowOverride All
                Require local
                Satisfy Any
        </Directory>

        ErrorLog /var/log/apache2/clientcal_error.log

        # Possible values include: debug, info, notice, warn, error, crit,
        # alert, emerg.
        LogLevel warn

        CustomLog /var/log/apache2/clientcal_access.log combined

</VirtualHost>
```

Then sudo a2ensite clientcal.conf to enable...
in the browser...

```
**This site can’t be reached

localhost refused to connect.
Search Google for localhost 8888
ERR_CONNECTION_REFUSED**
```

Looked at /var/www/html/clientcal/src/config.php for base dir hints, etc...

log details, just unable to put the pieces together....thoughts?

```
[Sun Apr 29 07:52:46.409806 2018] [:error] [pid 3258] [client 127.0.0.1:52932] PHP Fatal error:  Uncaught clientcal\\invalidConfig: invalid config name: the specified configName does not exist in /var/www/html/clientcal/src/config.php:154\nStack trace:\n#0 /var/www/html/clientcal/src/config.php(133): clientcal\\config::LoadAssoc('mysql')\n#1 /var/www/html/clientcal/lib/DAL/user.php(73): clientcal\\config->__construct('mysql')\n#2 /var/www/html/clientcal/app/Resources/controller/routine/getauth.php(13): clientcal\\userexists('')\n#3 /var/www/html/clientcal/app/Resources/controller/login.php(52): require('/var/www/html/c...')\n#4 /var/www/html/clientcal/web/login.php(8): require('/var/www/html/c...')\n#5 /var/www/html/clientcal/web/index.php(2): require('/var/www/html/c...')\n#6 {main}\n  thrown in /var/www/html/clientcal/src/config.php on line 154
```

Thank you,

**Comment by ackspony** [comment]
Apologies, the config preparation must be missing from the README.

There are two more steps.
Step 1: you need to create a few config files:
 * copy 'clientcal/app/config/clientcal/app-sample.php' to 'clientcal/app/config/clientcal/app.php'
 * copy 'clientcal/app/config/clientcal/customer-sample.php' to 'clientcal/app/config/clientcal/customer.php'
 * copy 'clientcal/app/config/clientcal/geoloc-sample.php' to 'clientcal/app/config/clientcal/geoloc.php'
 * copy 'clientcal/app/config/clientcal/mysql-sample.php' to 'clientcal/app/config/clientcal/mysql.php'

Step 2: you need to edit each the above files (especially mysql.php) appropriately.
You can skip "geoloc.php" if you don't need maps / reverse geocoding features.

**Comment by rrodstein** [comment]
Thank you for the tips, and your support!

Could you please provide the desired DocumentRoot, i.e.  is it
/var/www/html/clientcal/web
or
/var/www/html/clientcal/app/config/clientcal
?

Thank you

**Comment by rrodstein** [comment]
Thank you again for your support!

using DocumentRoot /var/www/html/clientcal/web

Files edited, and now:

```
[Tue May 01 09:05:42.247970 2018] [:error] [pid 19735] [client ::1:47190] PHP Fatal error:  Uncaught clientcal\\invalidConfigKey: invalid config key: the specified config key does not exist in /var/www/html/clientcal/src/config.php:95\nStack trace:\n#0 /var/www/html/clientcal/app/Resources/template/default/header.php(12): clientcal\\config->getValue('components_url_...')\n#1 /var/www/html/clientcal/lib/view.php(85): require('/var/www/html/c...')\n#2 /var/www/html/clientcal/lib/view.php(87): clientcal\\{closure}()\n#3 /var/www/html/clientcal/app/Resources/controller/login.php(66): clientcal\\header('Please Sign In')\n#4 /var/www/html/clientcal/web/login.php(8): require('/var/www/html/c...')\n#5 /var/www/html/clientcal/web/index.php(2): require('/var/www/html/c...')\n#6 {main}\n  thrown in /var/www/html/clientcal/src/config.php on line 95
```

**Comment by ackspony** [comment]
Nice work, looks like you got really close. 

My fix was to remove the only reference to the "components_url_prefix", switching to using a CDN URL for the using font-awesome CSS. So if you get the latest pull, you should be good to go without having to add in the above setting!

What was needed is for me to apply a backport of some fixes that were only devel branch to address this issue. (Don't bother with devel branch though yourself, it's about 50% broken).

As some background: the `$config["components_url_prefix"]` value is the URL prefix to "bower" components (it's not in the README, but there is a bower.json, which is was only used for font-awesome in the "master" branch). It can be disregarded for now as there was only one JS dependency that was managed by bower in the default template, and I've now removed it. I have to switch to "yarn" anyway as "bower" is now deprecated.

For good measure, I added the config setting to app-sample.php

```php
$config['components_url_prefix'] = "/components";
```

If you add this setting, it will make applying the future updates I have planned to clientcal easier, it will be compatible with eventual transition to yarn easier.

**Comment by ackspony** [comment]
Update... I removed all the bower stuff from the "master" branch.

**Comment by rrodstein** [comment]
Thank you again for you support! I cant wait to get the app running :-)

I've pulled down and staged the updated code, updated the above mentioned config files, and using using DocumentRoot /var/www/html/clientcal/web, I get the following error in the logs, still no page displaying in the browser, its blank:

```
[Tue May 01 13:34:19.871690 2018] [:error] [pid 19734] [client ::1:41364] PHP Fatal error:  require(): Failed opening required '/var/www/html/clientcal/app/config/../../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/clientcal/app/web-common.php on line 16
```

$ which php
/usr/bin/php

Do I need to add something to web-common.php resolve this?: (include_path='.:/usr/share/php') in /var/www/html/clientcal/app/web-common.php on line 16, i.e.
16    $autoloader = require require __DIR__.'/config/autoloader-path.php';

In my clientcal directory /var/www/html/clientcal/app/config/../..**/vendor/autoload.php** does not exist. 
```
M700:/var/www/html/clientcal/app/config/clientcal$ pwd
/var/www/html/clientcal/app/config/clientcal
M700:/var/www/html/clientcal/app/config/clientcal$ ls
app.php         balive.php    customer-sample.php  geoloc-sample.php  mysql-sample.php  template.php
app-sample.php  customer.php  geoloc.php           mysql.php          tables.php
```
Thoughts?

**Comment by ackspony** [comment]
Has composer run successfully in your local installation?

for example:
```
cd /var/www/html/clientcal
composer update
```

**Comment by ackspony** [comment]
Also, can you provide the output of listing the files in the root of your local installation?

```
cd /var/www/html/clientcal
ls
```

**Comment by rrodstein** [comment]
Hi,

"composer update" got the app/login page up-and-running!

Whats the default username and password, i.e. I tried the mysql root user account, and its password, no love....

Thank you!

**Comment by rrodstein** [comment]
```
M700:/var/www/html/clientcal$ ls
app  bin  composer.json  composer.lock  GPLv3  lib  LICENSE  README.md  src  vendor  web
```

**Comment by ackspony** [comment]
Indeed, I don't have a utility yet for managing users.

For now, user management must be performed manually by running SQL statements in the mysql console (or similar). 

The authentication logic searches for matches in the `user` table, which has `username` and `password` columns. The `password` column value cannot be plain text, it must be the return value of the mysql function PASSWORD(), as in the following example:

```sql
INSERT INTO 
   user
SET
   username='my_username',
   password=PASSWORD('mySecretPassword')
;
```

or to update an existing user:
```sql
UPDATE
   user
SET
   password=PASSWORD('myNewSecretPassword')
WHERE
   username='my_username'
;
```

**Comment by ackspony** [comment]
Also, note that you must do any login user management SQL statements (such as above) in the `clientcal` database (i.e. the same one set in `$config['dbname']` in 'app/config/clientcal/mysql.php'. The clientcal login user management is UNRELATED to mysql user access/permissions.

**Comment by rrodstein** [comment]
Getting close!
```
mysql> use clientcal
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> INSERT INTO 
    ->    user
    -> SET
    ->    username='clientcal',
    ->    password=PASSWORD('mypassword')
    -> ;
Query OK, 1 row affected, 1 warning (0.01 sec)
```
then I authenticate and get a blank page, and in the logs we see. 

```
[Tue May 01 16:25:44.812649 2018] [:error] [pid 8206] [client ::1:52790] PHP Fatal error:  Uncaught clientcal\\error: while get: FUNCTION clientcal.OLD_PASSWORD does not exist in /var/www/html/clientcal/lib/DAL/user.php:139\nStack trace:\n#0 /var/www/html/clientcal/app/Resources/controller/login.php(19): clientcal\\verifyuserinfo('clientcal', '**MyPasswordInTheClear**', '')\n#1 /var/www/html/clientcal/web/login.php(8): require('/var/www/html/c...')\n#2 /var/www/html/clientcal/web/index.php(2): require('/var/www/html/c...')\n#3 {main}\n  thrown in /var/www/html/clientcal/lib/DAL/user.php on line 139, referer: http://localhost:8888/
```

one click away from success!

**Comment by rrodstein** [comment]
Doug,

Thank you again for your support!

Respectfully,

**Comment by ackspony** [comment]
No problem, let me know if my latest fix resolved things.

Some background on the last issue, and the reason I had not caught it is likely due to the some differences between MariaDB and MySQL (I happen to use MariaDB at the moment, though it should work fine with MySQL). I had some legacy backwards compatible workaround logic involving the usage of `OLD_PASSWORD()` MySQL function in `lib/DAL/user.php` (which is ancient and no longer applicable or necessary).

**Comment by rrodstein** [comment]
A bit more to go... with the modified file, after authenticating, get a blank page, and in the logs:

```
[Tue May 01 16:53:27.145882 2018] [:error] [pid 19496] [client ::1:54798] PHP Fatal error:  Uncaught clientcal\\error: while get: FUNCTION clientcal.OLD_PASSWORD does not exist in /var/www/html/clientcal/lib/DAL/user.php:134\nStack trace:\n#0 /var/www/html/clientcal/app/Resources/controller/login.php(19): clientcal\\verifyuserinfo('clientcal', 'MyPasswordInTheCLear', '')\n#1 /var/www/html/clientcal/web/login.php(8): require('/var/www/html/c...')\n#2 /var/www/html/clientcal/web/index.php(2): require('/var/www/html/c...')\n#3 {main}\n  thrown in /var/www/html/clientcal/lib/DAL/user.php on line 134, referer: http://localhost:8888/
```
i.e. 
`134          throw new error(-4,"while get: " . mysql_error($my));`

**Comment by ackspony** [comment]
Try now, there shouldn't be any more `OLD_PASSWORD()` sneaking around.
